######################################################################
# Automatically generated by qmake (2.01a) ? 1? 29 15:27:40 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ButtonEvent.cpp
