######################################################################
# Automatically generated by qmake (2.01a) ? 1? 29 15:20:44 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloworld.cpp
