######################################################################
# Automatically generated by qmake (2.01a) ? 1? 30 10:36:11 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += proj_01.cpp
