######################################################################
# Automatically generated by qmake (2.01a) ? 1? 29 15:45:50 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CustomWidget-old.h CustomWidget.h
SOURCES += CustomWidget.cpp main.cpp
